meta_product_name: "Hife"
meta_title: "Hife - Driving Innovative & Sport Company Cultures"
meta_description: "Create and strengthen your company culture based on sports values"
meta_image: "photo_fb.jpeg" # should exist in `app/assets/images/`
twitter_account: "@hife"   # required for Twitter Cards
